# Generated by Django 4.1 on 2022-11-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childcompany',
            name='ranking',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2),
        ),
    ]
